### PR TITLE
Updated Upstream (Pufferfish)

### PR DESCRIPTION
**Pull request by granny**
Upstream has released updates that appear to apply and compile correctly

Pufferfish Changes:
pufferfish-gg/Pufferfish@c9f4e20 Final 1.20.4 Update
pufferfish-gg/Pufferfish@1f3ad02 Final 1.20.4 update, for realzies
pufferfish-gg/Pufferfish@b1ab664 Enable SIMD on java 21
pufferfish-gg/Pufferfish@0674c2b 1.21 compiles
pufferfish-gg/Pufferfish@98ea973 Fix 1.21 version checkers
pufferfish-gg/Pufferfish@68f859c Fix lambda/tick guard patch
pufferfish-gg/Pufferfish@eaa18d5 Updated Upstream (Paper)
pufferfish-gg/Pufferfish@1d72eea Updated Upstream (Paper)
pufferfish-gg/Pufferfish@1d3c743 Update pufferfish version detector stuff
pufferfish-gg/Pufferfish@5e30963 Fix crash bug
pufferfish-gg/Pufferfish@12571eb Use mojmapped paperclip jar instead (CI only)
pufferfish-gg/Pufferfish@4d16ae0 Drop a patch - moonrise includes it
pufferfish-gg/Pufferfish@52c2d05 Revert "Drop a patch - moonrise includes it"
pufferfish-gg/Pufferfish@bdb56f1 Fix entity interactions with fluids
pufferfish-gg/Pufferfish@469e5c1 Updated Upstream (Paper)
pufferfish-gg/Pufferfish@d75961f 1.21.1 Update (Updated Upstream (Paper))

### CODE REVIEW

**Comment by scaik** [comment]
i dont think there is a reason to wait as i didnt see any issues related to pufferfish 1.21 update both in discord and github issues page. everything seems to work flawlessly.

**Comment by Roan-V** [comment]
Exactly the reason for a wait :P
To see if any issues pop up in the meantime.

If it still looks fine after a few days then it will be merged :)

**Review by CyberFlameGO — APPROVED** [review]

**Comment by granny** [comment]
Will be merged into Purpur 1.21.1 builds once those get released

**Comment by Potothingi** [comment]
https://github.com/pufferfish-gg/Pufferfish/commit/bdb56f15001625bd73d883b87b71ba45bced5d27
You must include these changes before merging.

**Comment by CyberFlameGO** [comment]
If that is required it might also possibly be cool to include https://github.com/pufferfish-gg/Pufferfish/commit/52c2d0543d2cc5091ac43dd28bf6dd9f7b7e91ae judging from code at face value

**Comment by granny** [comment]
Yes, I will upstream to the most recent pufferfish commit before merging. That's a given.

**Comment by CyberFlameGO** [comment]
Awesome thanks so much!!!

**Review by GreeningSiren — APPROVED** [review]

**Pull request merged**
