### PR TITLE
Fix Important Issue Crash with Plugin or Datapack Generation

### PR DESCRIPTION
**Pull request by Euphillya**
Fix Paper#6028 submit to Paper but always not accepted

### CODE REVIEW

**Comment by katekerllenevich** [comment]
link to paper pr?

**Comment by Euphillya** [comment]
https://github.com/PaperMC/Paper/pull/6219

**Review by katekerllenevich — APPROVED** [review]

**Comment by SXRWahrheit** [comment]
Note that this doesn't actually fix the bug, per https://github.com/PaperMC/Paper/pull/6219, and an additional solution needs to be implemented.

**Comment by Euphillya** [comment]
> Notez que cela ne résout pas réellement le bogue, par [PaperMC / Paper # 6219](https://github.com/PaperMC/Paper/pull/6219), et une solution supplémentaire doit être implémentée.

This is the right solution, if the list is empty, how do you want to use it? Impossible, on vanilla it does not bug because all the trees have leaves.

**Comment by SXRWahrheit** [comment]
The correct result is to not cancel the generation. At the very least, the tree should generate without decorators.

**Comment by Euphillya** [comment]
Its only cancels the decoration.

**Pull request merged**
