### PR TITLE
Ver/1.19

### PR DESCRIPTION
**Pull request by 0x7d8**

### CODE REVIEW

**Comment by 0x7d8** [comment]
Bro I accidentally clicked that lol

**Comment by BillyGalbreath** [comment]
(┛ಠ_ಠ)┛彡┻━┻

**Comment by katekerllenevich** [comment]
If you are looking to create a fork of Purpur, let me direct you to the proper way using [Tentacles](https://github.com/PurpurMC/Tentacles)

**Comment by 0x7d8** [comment]
I dont want to create a that big fork anyway, just want to edit some things tomorrow for personal use

**Pull request closed without merging**
