### PR TITLE
maybe fix version problem

### PR DESCRIPTION
**Pull request by 0x7d8**
yes, see in #developers

### CODE REVIEW

**Comment by 0x7d8** [comment]
I did something wrong lmao

**Comment by 0x7d8** [comment]
did I? I dont understand Github

**Comment by 0x7d8** [comment]
At least this simple pr works in my fork to not break version info ¯\_(ツ)_/¯

**Comment by katekerllenevich** [comment]
Gotta rebase upon latest, I’ll just try to make this commit on my phone

**Pull request closed without merging**
