### PR TITLE
Build using Toothpick scripts

### PR DESCRIPTION
**Pull request by jpenilla**
This PR replaces the byof scripts with kotlin gradle buildscripts.

It uses a custom plugin, "Toothpick", which adds multiple gradle tasks to assist in patching and building the Purpur server and api.

The Toothpick plugin used in this PR is modified from [mikroskeemsrealm/Toothpick](https://github.com/mikroskeemsrealm/Toothpick), with some inspiration taken from [MiniDigger/Toothpick](https://github.com/MiniDigger/Toothpick).

gradle tasks added by Toothpick:
- `initGitSubmodules`
  - Initializes the Paper submodule if it has not been initialized yet
- `setupUpstream`
  - Apply Paper patches, i.e. `paper patch` in the Paper directory. Similar to `purpur up`. Will initialize the Paper submodule as a dependency of this task if necessary.
- `applyPatches`
  - Applies Purpur api and server patches on top of Paper, similar to `purpur patch`. If Paper is not yet setup that will be done as a dependency of this task.
- `rebuildPatches`
  - Deletes all patches and rebuilds them from the current state of the Purpur-Server and Purpur-API repos (`purpur rebuild`)
- `paperclip`
  - Builds the server, then builds a paperclip and saves it to the root project directory
- `updateUpstream`
  - Update and patch the Paper submodule. Would usually then be followed by `applyPatches`, resolving conflicts, then running `scripts/upstreamCommit.sh`
- `upstreamCommit`
  - Replacement for upstreamCommit.sh, will create a commit with the changes to the upstream submodule.
- `importMCDev`
  - This is a task which is depended upon by applyPatches, and would usually not be run manually. Imports needed NMS and library files that we want to make changes to.

Notable tasks not added by Toothpick:
- `build`
  - This is a standard gradle task which has been setup to build the server and api.
- `publishToMavenLocal`
  - Builds and publishes the `purpur` and `purpur-api` artifacts to the maven local repo.

Setting up a workspace is quite simple, just clone the repo and run the `applyPatches` task (`./gradlew applyPatches`)

### CODE REVIEW

**Comment by Titaniumtown** [comment]
When I run `./gradlew applyPatches`, it fails with this message:
```
> Task :importMCDev FAILED
>>> Importing mc-dev

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':importMCDev'.
> java.io.IOException: Cannot run program "git" (in directory "/home/simon/minecraft/Purpur-build-toothpick/Paper/Paper-Server"): error=2, No such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 881ms
1 actionable task: 1 executed
```
And I do indeed have git installed.

**Comment by BillyGalbreath** [comment]
> When I run `./gradlew applyPatches`, it fails with this message

I'm literally in the process of working on that (see convo in discord)

**Comment by Titaniumtown** [comment]
Oh, sorry.

**Comment by katekerllenevich** [comment]
heyo! on windows when i run `setupPaper` through git bash, it says something about needing to have virtualization enabled. not sure if thats a gradle thing in general, but this breaks a couple applications on my pc. not vital, but something to take note of.

**Pull request merged**
