### PR TITLE
Add option to disable scissor damage in liquid

### PR DESCRIPTION
**Pull request by JustDoom**
Added an option to disable scissor damage while in liquid. Some people found it annoying that they take damage when swimming clearing kelp. Made it optional just in case people like to get stabbed while swimming. It is enabled by default, think most players would not like it to be enabled

This is my first PR, please let me know if I did anything wrong. Sorry about the previous PR too, was trying to fix something and accidentally deleted it which closed the PR

### CODE REVIEW

**Comment by BrycensRanch** [comment]
things that modify behavior are typically disabled by default

**Comment by encode42** [comment]
That is true! The current defaults would result in an unexpected behavior change; scissors no longer doing damage in water. Easy fix though!

**Comment by BrycensRanch** [comment]
Yeah! thank you for contributing to Purpur to make it more awesome 🌋

**Comment by JustDoom** [comment]
Fixed!

**Review by granny — CHANGES_REQUESTED** [review]
Looks good to me! It looks like you're checking both water & lava but the option is labeled as "water". My request is to create a separate option specifically for lava as well.

**Comment by JustDoom** [comment]
Fixed it! There are now two options

**Review by granny — APPROVED** [review]
LGTM

**Pull request merged**
