### PR TITLE
Add support for Proxy Protocol

### PR DESCRIPTION
**Pull request by PanSzelescik**
This PR adds support for Proxy Protocol in Purpur.
More info in Paper PR, which is still open: https://github.com/PaperMC/Paper/pull/7710

### CODE REVIEW

**Comment by katekerllenevich** [comment]
Possible problem, if paper merged this then we have to maintain a config migration for god knows how long on this.

**Comment by PanSzelescik** [comment]
Right, is it better to add config to Paper? Not to Purpur?

**Comment by katekerllenevich** [comment]
I'll be honest I'm not certain, would prefer advice from others

**Comment by encode42** [comment]
IMO low-level changes such as this are more fit in Paper

**Comment by katekerllenevich** [comment]
I agree

**Comment by encode42** [comment]
As discussed, this feature is a better fit for Paper. If your upstream PR is not accepted, this PR can be revisited!

**Pull request closed without merging**
