### PR TITLE
Update the "changing the blocks that turn into paths" defaults to reflect the vanilla defaults.

### PR DESCRIPTION
**Pull request by Roan-V**

### CODE REVIEW

**Comment by Euphillya** [comment]
Hello, I don't understand why you removed the dirt block?

**Comment by Roan-V** [comment]
Because minecraft doesn't do that in vanilla https://minecraft.fandom.com/wiki/Grass_Path

This is just an edit of the default config options, you can obviously still add dirt to that list on your own server ^_^

**Comment by 12emin34** [comment]
The dirt block was likely accidentally left in when Billy made the list configurable

**Review by encode42 — CHANGES_REQUESTED** [review]
Coarse dirt and mycelium can only be used to make paths in 1.17, 1.16 only has grass

**Comment by Roan-V** [comment]
Ah you're right, I just tested it
The wiki lied to me >:(

**Review by encode42 — APPROVED** [review]

**Comment by encode42** [comment]
Keep in mind that you can't edit patches by hand or else the index doesn't match up, patches must be edited from the source

**Pull request merged**
