### PR TITLE
Switch to NogyangSpigot Fork

### PR DESCRIPTION
**Pull request by Outfit8TSB**
i checked out NogyangSpigot and the api patched correctly as a submodule.
from future purpur builds instead of Using Paper as a upstream, Use NogyangSpigot as a submodule.

Tasks:

- [ ] Fix Server Patches

### CODE REVIEW

**Comment by Euphillya** [comment]
I don't think your PR will be accepted as it is, because we will be depending on another project that might be abandoned in the future. Otherwise, create a patch that implements their functionality as we did with:
- Tuinity
- Airplane
- PufferFish

**Comment by YouHaveTrouble** [comment]
Not happening.

**Comment by Outfit8TSB** [comment]
NOTE:  i don't think the patch is a good idea because NogyangSpigot Project will literally fall like Yatopia if we do that. (This is why i set it on draft.)

**Comment by YouHaveTrouble** [comment]
Please refrain from opening PRs you don't want merged

**Comment by Outfit8TSB** [comment]
Dude i was literally talking to euphillya. didn't expect that. If NogyangSpigot Implements Tuinity API, Airplane API, Pufferfish API. Pufferfish Server, Airplane Server but if we do that, we are going to collapse like "Yatopia". But i considered implementing tuinity + airplane + pufferfish in my project.

**Comment by granny** [comment]
That's flawed from the start. Tuinity was merged into Paper, which means it's dead. Pufferfish is a continuation of Airplane, which means Airplane is obsolete. That leaves just Pufferfish (which still hasn't updated to 1.20.6)

**Comment by Outfit8TSB** [comment]
Yes, in fact, if i do what euphilla said, We are going to more look like yatopia. See 
https://github.com/kennytv/yaptapia for more

**Comment by Euphillya** [comment]
> Yes, in fact, if i do what euphilla said, We are going to more look like yatopia. See https://github.com/kennytv/yaptapia for more

I never said to make a Yatopia 2, just do it as it's been done for years like this: https://github.com/PurpurMC/Purpur/blob/ver/1.20.6/patches/unapplied-server/0001-Pufferfish-Server-Changes.patch

**Comment by granny** [comment]
I see absolutely zero benefit in switching to your fork. Please refrain from bringing this up in the future.

**Pull request closed without merging**
