### PR TITLE
Adding russian characters in nickname support

### PR DESCRIPTION
**Pull request by BrokenFG**
This PR allows players with russian characters in the nickname to connect to the server

### CODE REVIEW

**Comment by katekerllenevich** [comment]
Does Mojang allow this in their usernames?

**Comment by YouHaveTrouble** [comment]
> Does Mojang allow this in their usernames?

I'm 99.9% sure they do not. Only english alphanumeric characters and `_` as far as I know.

**Comment by BrokenFG** [comment]
Most Russian servers support Russian nicknames, but there is no possibility to connect with such a nickname in this fork. I think there should be such an opportunity.

**Comment by encode42** [comment]
As Russian usernames are only possible on offline mode servers and with cracked players, this will not be accepted. Purpur does not support offline mode, nor will we add features that apply specifically to it.

**Pull request closed without merging**
