### PR TITLE
Add suppress offline mode warning

### PR DESCRIPTION
**Pull request by Kale-Ko**

### CODE REVIEW

**Comment by Kale-Ko** [comment]
Why?

**Comment by BillyGalbreath** [comment]
We don't suppress useful information

**Comment by Kale-Ko** [comment]
How is it useful?

**Comment by Kale-Ko** [comment]
Its just an annoyance when you are running a bungee server

**Comment by katekerllenevich** [comment]
Its so we know who not to provide support for.

**Comment by BillyGalbreath** [comment]
Join us on Discord if you'd like to have a conversation about it (or search it up in there to see previous discussions on it).

**Comment by Kale-Ko** [comment]
> Its so we know who not to provide support for.

Ah, fair enough. Thanks anyways

**Comment by BillyGalbreath** [comment]
That's actually not any of the valid reasons we don't do this. We will only suppress pointless information, not useful information. And these offline messages (whether the server is in offline mode for piracy, testing, or behind a proxy) are very important information the server admins need to read and be aware of. It doesn't matter how annoying it is, it is important information, so it will never be suppressed by us.

**Pull request closed without merging**
