### PR TITLE
fix crucial crash bug

### PR DESCRIPTION
**Pull request by YouHaveTrouble**
also fixes lag

### CODE REVIEW

**Review by katekerllenevich — APPROVED** [review]
omg my tps is now 500!!!11!!

**Comment by encode42** [comment]
this fixed my entire server network bungee yatopia tps fast mspt async working very well with multithreading no crash no lag very good.

**Comment by JLyne** [comment]
Excuse me but this fix has caused my server to run way too fast and this is messing with the timings on my 67000 hopper farm. Please revert thanks.

**Comment by Euphillya** [comment]
OMG Mojang has push your PR, you are great

**Review by TMUniversal — APPROVED** [review]

**Comment by 12emin34** [comment]
This made my server so fast that it went into the fifth dimension.

**Comment by EuanM199** [comment]
This allowed me to run 10000 players on one 1GB server!!!!!

**Review by jpenilla — APPROVED** [review]
lgtm, pending review from Billy before merge on such a critical change.

**Comment by compieter-gh** [comment]
My tps just whent over 9000 Lol Best fix ever

**Comment by Sculas** [comment]
> My tps just whent over 9000 Lol Best fix ever

you just ruined the joke 😔

**Comment by EuanM199** [comment]
What joke?, this is a serious fix

**Pull request closed without merging**
