### PR TITLE
Changed the logo of Tuinity to that of Purpur!

### PR DESCRIPTION
**Pull request by Euphillya**
This patch adds multithreading to anything and everything: P

### CODE REVIEW

**Comment by Euphillya** [comment]
image
This Logo

**Review by YouHaveTrouble — APPROVED** [review]
glorious

**Review by jpenilla — CHANGES_REQUESTED** [review]
For reference, this is the image file in the PR:
image

When zoomed out and small it looks fine but when zooming in/enlarging the image there's some noticeable black specks. Not sure where you got the base image from (guessing maybe the Discord icon?), but here is the source image: [link](https://user-images.githubusercontent.com/11360596/113974227-6d814400-97f2-11eb-84ea-1145bb3181cb.png)
You can slap a squid on top of it if you want, then downscale to 200x200, and it should come out a bit better then the Discord icon rip.

Once you update the PR, it would be appreciated if you could upload the new image you use here on GitHub so we can look at it without patching.

Lastly, instead of creating a new patch for this, please squash it into the Rebrand patch.

**Comment by Euphillya** [comment]
https://github.com/pl3xgaming/Purpur/pull/274

**Pull request closed without merging**
