### PR TITLE
Add Velocity in Online Mode.

### PR DESCRIPTION
**Pull request by Euphillya**
Bungee was added, why not velocity too

### CODE REVIEW

**Comment by BillyGalbreath** [comment]
`PaperConfig.isProxyOnlineMode()` already checks for velocity, too. The bug i think you are trying to fix is in the Timings Viewer code, not the server software.

**Comment by Euphillya** [comment]
Yes its my idea of this patch, i am not verry check sorry

**Comment by Roan-V** [comment]
https://github.com/aikar/timings/commit/63fcbeb2772022da8dca5def7ac400cc1e1d49f1
How is this related then? It seems like support has already been added

**Comment by BillyGalbreath** [comment]
> [aikar/timings@63fcbeb](https://github.com/aikar/timings/commit/63fcbeb2772022da8dca5def7ac400cc1e1d49f1)
> How is this related then? It seems like support has already been added

My fork of the Timings Viewer is way older than that commit.

**Comment by Roan-V** [comment]
So you should update :P

**Comment by BillyGalbreath** [comment]
That's the plan. Eventually ;)

**Pull request closed without merging**
