### PR TITLE
Fix #1181

### LINKED ISSUE #1181: addPotionEffect() does not work as intended with Darkness
### Spark link

https://spark.lucko.me/YMnoyysEZl

### Expected behavior

The vanilla darkness effect, such as `/effect give @s darkness 15` grants the player the Skulk Shrieker's `DARKNESS` effect to the player for 15 seconds.

### Observed/Actual behavior

When Skript tries to do this, such as with:
```
command /heartbeat <player>:
    trigger:
        apply potion of darkness to arg 1 for 15 seconds
```
The client's screen goes entirely black, rather than apply the effect correctly.
image

### Steps/models to reproduce

Create a fresh server running Purpur (tested builds 1752, 1800, and latest 1835), and place Skript 2.6.3 in the plugins folder.
Utilize this Skript to test the effect via the `/heartbeat <in-game player>` command:
[heartbeat.txt](https://github.com/PurpurMC/Purpur/files/9934008/heartbeat.txt)
(save as a skript in the `/plugins/Skript/scripts/` folder as `heartbeat.sk` to execute)

### Purpur version

Current: git-Purpur-1835 (MC: 1.19.2)*
Previous: git-Purpur-1752 (MC: 1.19.2)
* You are running the latest version

Also tested with Purpur-1800 and Purpur-1752 after initial latest tests failed.

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Tested with the same setup using Paper server setups had no issues; only upgrading from Paper to Purpur on various 1.19.2 builds is when this issue appeared.

Multiple users have confirmed the issue using vanilla, 1.19.2 clients with no mods, shaders or resource packs active.

Skript community has been made aware of the behavior and recommended this be explored here, as the issue is only able to be reproduced on a Purpur server and not native to Paper nor Skript itself.

### PR DESCRIPTION
**Pull request by BillyGalbreath**
Possible fix for #1181

I'm not going to learn Skript in order to test this, so this is a PR until someone can test and verify.

### CODE REVIEW

**Comment by MelnCat** [comment]
Is there going to still be a way to use the old darkness effect applying effect?

**Comment by BillyGalbreath** [comment]
> Is there going to still be a way to use the old darkness effect applying effect?

If this fixes the issue, yes. Just send an empty optional for the factor data (whatever that is).

All this fix does is fix the mess of overloaded ctors from this patch which incorrectly set empty optionals instead of instanced factor data.

**Comment by MelnCat** [comment]
You can't specify factor data using the API

**Comment by Brickgard** [comment]
> I'm not going to learn Skript in order to test this, so this is a PR until someone can test and verify.

Understandable; would a drag-and-drop solution into the /plugins/ folder be adequate to help you test/verify?
[Skript.zip](https://github.com/PurpurMC/Purpur/files/9944838/Skript.zip)
^ This unzipped in your /plugins/ folder would allow the `/heartbeat` command in-game to test its functionality.

**Comment by RhythmicSys** [comment]
Tested, didn't seem to fix the issue unless I built the jar incorrectly

**Comment by BillyGalbreath** [comment]
Tested and confirmed fixed.

> You can't specify factor data using the API

Bummer. Use NMS then. :P

**Pull request merged**
