### PR TITLE
fix offline mode message

### PR DESCRIPTION
**Pull request by Oharass**
Purpur has a FLAWED check for if bungee proxy online is in use. isProxyOnlineMode is TRUE BY DEFAULT. Even without bungee enabled. This is big issue. It does not support velocity either. This adds.

### CODE REVIEW

**Comment by katekerllenevich** [comment]
isProxyOnlineMode checks org.spigotmc.SpigotConfig.bungee unless i'm mistaken

**Comment by Euphillya** [comment]
Yes it checks well:
https://github.com/PaperMC/Paper/blob/06db5d08b08c4f53fea9cb322127b3a3311bbcd9/patches/server/0103-Add-setting-for-proxy-online-mode-status.patch#L30

**Comment by Oharass** [comment]
Yes. This supports velocity. The message contains velocity but velocity is not supported.

```java
                DedicatedServer.LOGGER.warn("Whilst this makes it possible to use BungeeCord or Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose."); // Purpur
                DedicatedServer.LOGGER.warn("Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.");
```

**Comment by Euphillya** [comment]
https://github.com/PaperMC/Paper/blob/cc6fd371b2d1ab2ad1df85789b143f04a17c1468/patches/server/0280-Add-Velocity-IP-Forwarding-Support.patch#L33

Velocity supported

**Pull request closed without merging**
