### PR TITLE
Fix attribute spam for bats

### PR DESCRIPTION
**Pull request by Camotoy**
Addresses #728

Since the client doesn't need these attributes, indicate that they shouldn't be sent. This doesn't appear to impact the bat from being rideable.

Feel free to contact me on Discord! Camotoy#5533

### CODE REVIEW

**Review by encode42 — COMMENTED** [review]
LGTM, needs a rebase though

**Review by katekerllenevich — APPROVED** [review]
LGTM, I would like a review from @BillyGalbreath

**Comment by encode42** [comment]
Re-open this on the 1.18.1 branch, then it is ready to merge

**Comment by Camotoy** [comment]
Someone else is free to do that; I'm not sure if I'll get around to it anytime soon.

**Pull request closed without merging**
